### ISSUE TITLE
Vehicles won't move if collide with another.

### ISSUE THREAD

**Issue by CodeCado** [SmashPhil/Vehicles#23]
Title is self explanatory. When colliding from the front, if both vehicles are facing each other they won't move anymore.

![imagen](https://user-images.githubusercontent.com/77220489/104114928-96c03000-52e8-11eb-87d7-4e412e0b7784.png)

Only happens if they are facing. If they collide from behind, the last one just stops but can recieve new orders.
Sparrow's affected too.

**Comment by SmashPhil** [comment]
Ah yes, an old bug I definitely didn't just forget about. Thanks for reminding me 👍
