### ISSUE TITLE
Game-breaking bug.

### ISSUE THREAD

**Issue by CodeCado** [SmashPhil/Vehicles#24]
Got stuck in this position. 

![unknown](https://user-images.githubusercontent.com/77220489/104115445-4c41b200-52ee-11eb-9b6d-8bffa7ca91a7.png)

I deconstructed the four walls behind the tank and it gave me errors when deconstructed the fourth.

![unknown](https://user-images.githubusercontent.com/77220489/104115475-90cd4d80-52ee-11eb-90e2-f6969c52719a.png)

I fixed it by pausing and deleting the tank via dev tools. Tried recreating the bug and I couldn't.
Here's the log.
https://gist.github.com/HugsLibRecordKeeper/37f16811e88603c8c8567b7f04c43959

**Comment by SmashPhil** [comment]
I see what's causing the issue. I'll make note of it, but this will end up being a pretty rare occurrence. This will only be triggered by the tank taking an immediate diagonal turn right next to the car. Thanks.
