### ISSUE TITLE
Caravan vehicles not working.

### ISSUE THREAD

**Issue by CodeCado** [SmashPhil/Vehicles#25]
When trying to make a caravan by selecting the option "Form vehicle caravan" the UI stops working and I get some errors.

![unknown](https://user-images.githubusercontent.com/77220489/104117028-ad708200-52fc-11eb-85af-d3ba69587995.png)
Related to that.
https://gist.github.com/ba528e75dd88c1044d095f3d8c3b5452

Also, tried to launch Sparrow and got something weird.

![unknown](https://user-images.githubusercontent.com/77220489/104117077-f0325a00-52fc-11eb-820a-6a10ed411e26.png)

Every time I pressed Launch it spawned a new entitiy on the world map. Nothing moved, just gave me errors.

![unknown](https://user-images.githubusercontent.com/77220489/104117089-13f5a000-52fd-11eb-8f84-84580b15c451.png)

https://gist.github.com/b61e5c9f0e0e278ddc7ce81235fc32c7

**Comment by SmashPhil** [comment]
I can only fix what I can see in the logs, and right now those ones are cluttered with leftover messages. I'm closing the ticket for the issues I did manage to find in the logs (and fix). If any of the ones that I didn't see in the logs pop up again then you can go ahead and make a new ticket.
