### ISSUE TITLE
Fishing Boat doesn't move through Built Shallow Water

### ISSUE THREAD

**Issue by alexbb721** [SmashPhil/Vehicles#27]
Fishing boat doesn't move through built shallow water

Build fishing boat
Build shallow water
"Ship cannot reach this are"

ss before shallow water is built
![image](https://user-images.githubusercontent.com/52507651/104124407-9b1c3580-5348-11eb-83d5-f2b6b1ed1e84.png)
![image](https://user-images.githubusercontent.com/52507651/104124413-9eafbc80-5348-11eb-9caf-2fb872c2c9e3.png)
Shallow Water built but fishing boat doesn't recognise it as water

**Comment by SmashPhil** [comment]
Shallow water will be removed for the final release. In fact, I'll be removing it with the next update. It's not a bug with the boat it's a bug with regions not dirtying / rebuilding.. which carried over from Boats.  If you are looking for a mod to be able to change terrain I recommend Fertile Fields, as this water buildable will be gone when I update sometime today. Thanks
