### ISSUE TITLE
Tank doesn't recognise explosive shells (or say what ammo to use)

### ISSUE THREAD

**Issue by alexbb721** [SmashPhil/Vehicles#28]
The Tank isn't showing what ammo to use, and (if High explosive shells are the right ammo) doesn't recognise it in the cargo

Build Tank
Load cargo, load crew
Tank doesn't recognise ammo for the main gun (however the machine gun works perfectly)

![image](https://user-images.githubusercontent.com/52507651/104124482-0f56d900-5349-11eb-8772-44d5249a1ebe.png)

goes through the animations of firing, but nothing is shot from the barrel.

**Comment by SmashPhil** [comment]
The tank uses MkX shells, you can spawn them via devmode but this does bring up a good point. I'll need to include (most likely in the workshop description or ingame) what each cannon def uses for ammo.
