### ISSUE TITLE
Repair doesn't work/Upgrade window doesn't fit screen

### ISSUE THREAD

**Issue by CodeCado** [SmashPhil/Vehicles#29]
I know you already know about these, so I'll put them together so I don't flood the place.

**Repair doesn't work.**

When repairing a damaged vehicle, the pawn changes its status to "Standing", an error pops up and the vehicle doesn't get any repair.

![imagen](https://user-images.githubusercontent.com/77220489/104134719-47badf00-536a-11eb-94c8-aaec5431e588.png)
https://gist.github.com/71ef8f410103b4b7867f0dcf2ee8d15a

**Upgrade window doesn't fit the screen.**

Resolution: 1366x768.

![imagen](https://user-images.githubusercontent.com/77220489/104134778-7f298b80-536a-11eb-8764-ce229d1b270f.png)

**Comment by SmashPhil** [comment]
Repair one is fixed. To get the latest update you'll have to restart your game. 

I'll have to redo the UpgradeTree window in order to account for different resolutions, but yea this is an issue I forgot about from awhile back. Thanks

**Comment by tanypredator** [comment]
I've got another error from "upgrade" button:
Exception filling tab Vehicles.UI.ITab_Vehicle_Upgrades: System.InvalidOperationException: Upgrade ITab on Pawn without CompUpgradeTree: Row Boat
  at Vehicles.UI.ITab_Vehicle_Upgrades.get_SelPawnUpgrade () [0x0005d] in <3cb54626425f493e93e23d616a8a43b3>:0 
  at Vehicles.UI.ITab_Vehicle_Upgrades.FillTab () [0x00094] in <3cb54626425f493e93e23d616a8a43b3>:0 
  at Verse.InspectTabBase+<>c__DisplayClass14_0.<DoTabGUI>b__0 () [0x00039] in <d72310b4d8f64d25aee502792b58549f>:0 
Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.<>c__DisplayClass14_0:<DoTabGUI>b__0()
Verse.ImmediateWindow:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by SmashPhil** [comment]
Closing the issue for the repair and and itab bugs. I'll be redesigning the Upgrade window soon to accommodate lower resolutions. Thanks
