### ISSUE TITLE
Sparrow bugs.

### ISSUE THREAD

**Issue by CodeCado** [SmashPhil/Vehicles#30]
Found some bugs relating the Sparrow when trying to recreate the other one.

If you Launch from colony and select your colony again to land somewhere else, it creates a new entity on the world map even when the Sparrow just landed. There's no error popping up.

There's a list of things happening when you keep trying to do things after that, which makes the whole problem even worse.

![imagen](https://user-images.githubusercontent.com/77220489/104135572-088f8c80-5370-11eb-9eb5-f8b3b70d4068.png)

The log is right after landing and creating the extra entity on the world map.
https://gist.github.com/cb0f80f91b8bcfdc775ee42137ca1a6b

**Comment by CodeCado** [comment]
Same thing with transport pod.

**Comment by SmashPhil** [comment]
This is fixed now, however I'm going to leave it open as I would like to transition over to disallowing picking destinations within 1 or 2 tiles of your map. Just seems weird to teleport from one side of the map to the other or even bomb your map immediately after takeoff. Thanks for the report.

**Comment by XidonEye** [comment]
maybe a related issue. Two Sparrows just try to land on the same Spot, comming from worldmap, and the Game Crashed to Desktop. No other Mods.

**Comment by SmashPhil** [comment]
> maybe a related issue. Two Sparrows just try to land on the same Spot, comming from worldmap, and the Game Crashed to Desktop. No other Mods.

If you intentionally picked those 2 spots and that happened then I'll add a spot reservation for shuttles that intend to land in that spot. Thanks

**Comment by SmashPhil** [comment]
Fixed the bug where notifications of being crushed by a vehicle (received by another vehicle) would cause the game to hang. This is the same that was causing the two sparrows landing in the same spot to freeze up.

**Comment by SmashPhil** [comment]
I'm gonna close this ticket and open a new one for the feedback about having a minimum launch distance. The bugs described here are all fixed up. Thanks!
