### ISSUE TITLE
Loading and unloading cargo jobs.

### ISSUE THREAD

**Issue by CodeCado** [SmashPhil/Vehicles#31]
When two or more pawns with hauler job are available, they will load at the same time whatever the cargo is.
The input was 5 meals and two haulers were doing the job.

![unknown](https://user-images.githubusercontent.com/77220489/104136549-b94c5a80-5375-11eb-9f42-59ba8e39f1fe.png)
![unknown](https://user-images.githubusercontent.com/77220489/104136562-d2eda200-5375-11eb-9a56-5bf89df4fb2e.png)

It ended up with twice the input this case but there's no limit on pawns doing the same thing, so it gets messy when there are more of them.

![unknown](https://user-images.githubusercontent.com/77220489/104136604-13e5b680-5376-11eb-8506-99702af4508b.png)

At the same time, unloaded objects will remain under the vehicle and won't let pawns haul them. If they happen to take the job, automatically changes them to a Standing status.

![unknown](https://user-images.githubusercontent.com/77220489/104136730-b56d0800-5376-11eb-89c4-f4298087a1b3.png)

**Comment by Roshag** [comment]
Loading doesn't seem to be fixed while unloading is fine. 
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/4922267/480127a5-6a0e-41f1-8f34-8ee685932597)
