### ISSUE TITLE
Land transport in raid from the sea edge of map

### ISSUE THREAD

**Issue by tanypredator** [SmashPhil/Vehicles#32]
Raiders came from the sea edge of map with a car.

Sorry for dark screenshot, that happened at night. Unfortunately, it is night here irl too, so I cannot check what will happen next now ) Save and mod list attached.

[Medieval Settlement5.zip](https://github.com/SmashPhil/Vehicles/files/5826502/Medieval.Settlement5.zip)

[Jan2021.zip](https://github.com/SmashPhil/Vehicles/files/5826510/Jan2021.zip)
![image](https://user-images.githubusercontent.com/51823842/104850519-73f9d100-5911-11eb-8a2e-d391e3fd0832.png)

**Comment by tanypredator** [comment]
[Mods.zip](https://github.com/SmashPhil/Vehicles/files/5826519/Mods.zip)
Two mods that I have not from Steam

**Comment by SmashPhil** [comment]
Raiders (or incidents in general) are not fully implemented yet and I have not set them to spawn / replace with vehicles. Did you spawn this via debug actions?

**Comment by tanypredator** [comment]
No, it just happened. There were some errors, I didn't think that they will be cleaned after save load :(
Now I have loaded the save, clicked the car and got 2 new errors:

[Vehicles] Logging Errors for Multithreaded pathing:
Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
Vehicles.AI.Vehicle_PathFollower:GenerateNewPathThreaded()
Vehicles.AI.Vehicle_PathFollower:TrySetNewPath()
Vehicles.AI.Vehicle_PathFollower:TryEnterNextPathCell()
Vehicles.AI.Vehicle_PathFollower:PatherTick()
Vehicles.VehiclePawn:Tick()
Verse.TickList:Verse.TickList.Tick_Patch2(TickList)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()


InnerException 1: An item with the same key has already been added. Key: (Vehicles.VehicleDef, speed) 
StackTrace:   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Vehicles.SettingsCache.GetCachedField (System.Type type, System.String name) [0x00027] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at Vehicles.SettingsCache.TryGetValue[T] (Vehicles.VehicleDef def, System.Type containingType, System.String fieldName, T fallback) [0x00001] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at Vehicles.VehiclePawn.get_StatMoveSpeed () [0x0001b] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at Vehicles.VehiclePawn.get_ActualMoveSpeed () [0x00001] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at Vehicles.Upgrades.VehicleMoveSpeedUpgradeModifier (System.Boolean diagonal, Verse.Pawn __instance, System.Int32& __result) [0x00011] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at (wrapper dynamic-method) Verse.Pawn.Verse.Pawn.TicksPerMove_Patch4(Verse.Pawn,bool)
  at Verse.Pawn.get_TicksPerMoveCardinal () [0x00000] in <d72310b4d8f64d25aee502792b58549f>:0 
  at Vehicles.AI.VehiclePathFinder.FindVehiclePath (Verse.IntVec3 start, Verse.LocalTargetInfo dest, Verse.TraverseParms traverseParms, System.Threading.CancellationToken token, Verse.AI.PathEndMode peMode, System.Boolean waterPathing) [0x004a4] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at Vehicles.AI.VehiclePathFinder.FindVehiclePath (Verse.IntVec3 start, Verse.LocalTargetInfo dest, Vehicles.VehiclePawn pawn, System.Threading.CancellationToken token, Verse.AI.PathEndMode peMode) [0x00054] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at Vehicles.AI.Vehicle_PathFollower.GenerateNewPath (System.Threading.CancellationToken token) [0x00032] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at Vehicles.AI.Vehicle_PathFollower+<>c__DisplayClass33_0.<GenerateNewPathThreaded>b__1 () [0x00011] in <f8b7e55e3ded43eaa654e838f11b8160>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <567df3e0919241ba98db88bec4c6696f>:0  
Source: mscorlib
Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
Vehicles.AI.Vehicle_PathFollower:GenerateNewPathThreaded()
Vehicles.AI.Vehicle_PathFollower:TrySetNewPath()
Vehicles.AI.Vehicle_PathFollower:TryEnterNextPathCell()
Vehicles.AI.Vehicle_PathFollower:PatherTick()
Vehicles.VehiclePawn:Tick()
Verse.TickList:Verse.TickList.Tick_Patch2(TickList)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()


By the way, I have mods that can interfere (and that obviously interfere with each other) - Giddy Up and ZLevels, and also Biomes!, that contains Swimming Kit in it.

**Comment by SmashPhil** [comment]
> No, it just happened. There were some errors, I didn't think that they will be cleaned after save load :(
> Now I have loaded the save, clicked the car and got 2 new errors:
> 
> [Vehicles] Logging Errors for Multithreaded pathing:
> Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
> Vehicles.AI.Vehicle_PathFollower:GenerateNewPathThreaded()
> Vehicles.AI.Vehicle_PathFollower:TrySetNewPath()
> Vehicles.AI.Vehicle_PathFollower:TryEnterNextPathCell()
> Vehicles.AI.Vehicle_PathFollower:PatherTick()
> Vehicles.VehiclePawn:Tick()
> Verse.TickList:Verse.TickList.Tick_Patch2(TickList)
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:UpdatePlay()
> Verse.Root_Play:Update()
> 
> InnerException 1: An item with the same key has already been added. Key: (Vehicles.VehicleDef, speed)
> StackTrace: at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <567df3e0919241ba98db88bec4c6696f>:0 at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0
> at Vehicles.SettingsCache.GetCachedField (System.Type type, System.String name) [0x00027] in :0
> at Vehicles.SettingsCache.TryGetValue[T] (Vehicles.VehicleDef def, System.Type containingType, System.String fieldName, T fallback) [0x00001] in :0
> at Vehicles.VehiclePawn.get_StatMoveSpeed () [0x0001b] in :0
> at Vehicles.VehiclePawn.get_ActualMoveSpeed () [0x00001] in :0
> at Vehicles.Upgrades.VehicleMoveSpeedUpgradeModifier (System.Boolean diagonal, Verse.Pawn __instance, System.Int32& __result) [0x00011] in :0
> at (wrapper dynamic-method) Verse.Pawn.Verse.Pawn.TicksPerMove_Patch4(Verse.Pawn,bool)
> at Verse.Pawn.get_TicksPerMoveCardinal () [0x00000] in :0
> at Vehicles.AI.VehiclePathFinder.FindVehiclePath (Verse.IntVec3 start, Verse.LocalTargetInfo dest, Verse.TraverseParms traverseParms, System.Threading.CancellationToken token, Verse.AI.PathEndMode peMode, System.Boolean waterPathing) [0x004a4] in :0
> at Vehicles.AI.VehiclePathFinder.FindVehiclePath (Verse.IntVec3 start, Verse.LocalTargetInfo dest, Vehicles.VehiclePawn pawn, System.Threading.CancellationToken token, Verse.AI.PathEndMode peMode) [0x00054] in :0
> at Vehicles.AI.Vehicle_PathFollower.GenerateNewPath (System.Threading.CancellationToken token) [0x00032] in :0
> at Vehicles.AI.Vehicle_PathFollower+<>c__DisplayClass33_0.b__1 () [0x00011] in :0
> at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <567df3e0919241ba98db88bec4c6696f>:0
> at System.Threading.Tasks.Task.Execute () [0x00010] in <567df3e0919241ba98db88bec4c6696f>:0
> Source: mscorlib
> Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
> Vehicles.AI.Vehicle_PathFollower:GenerateNewPathThreaded()
> Vehicles.AI.Vehicle_PathFollower:TrySetNewPath()
> Vehicles.AI.Vehicle_PathFollower:TryEnterNextPathCell()
> Vehicles.AI.Vehicle_PathFollower:PatherTick()
> Vehicles.VehiclePawn:Tick()
> Verse.TickList:Verse.TickList.Tick_Patch2(TickList)
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:UpdatePlay()
> Verse.Root_Play:Update()
> 
> By the way, I have mods that can interfere (and that obviously interfere with each other) - Giddy Up and ZLevels, and also Biomes!, that contains Swimming Kit in it.

Swimming Kit is 100% causing the cars (and pawns) to spawn at the edge of the map, but the fact you're getting the armored raid is an issue in and of itself. Turns out, I forgot to comment out the incident def since I stopped working on that part a couple weeks ago. Woops. In any case, these are separate incidents altogether so if this occurs I recommend you just turn on devmode and destroy the vehicle asap cause sometimes there can be issues with the AI's pathing that will lead to a CTD. In any case, I'll be reworking the entire raid system anyways.

**Comment by tanypredator** [comment]
One more thing I noticed is that raids became much stronger for my usual difficulty - now 7 raiders, some with guns, are going to attack my 6 pawns, and previously 4 or 5 raiders came by land, but without transport (they were at low tech level), but that is still too much for the beginning of game.

**Comment by SmashPhil** [comment]
If there's no vehicle, it's a normal raid. I'm not touching anything with the normal raid events.

**Comment by tanypredator** [comment]
Of this 7, 3 are in vehicles, maybe they are not counted.
Interesting - they all prepare near the edge of map, except the car that immediately headed to land )

**Comment by SmashPhil** [comment]
Yea, that's the case for right now. But again, raiders / traders are not supposed to be in there yet so the balancing is irrelevant as I plan to go a different route regarding raids anyways :)
