### ISSUE TITLE
Red error related to compatibility patching with Dual Wielding on startup.

### ISSUE THREAD

**Issue by FamineOLaymine** [SmashPhil/Vehicles#33]
Just happens upon starting the game with this mod loaded, I don't have Dual Wielding in my mod list.

Logs here: https://gist.github.com/fb925eac997ecc39c32b3c121d6c2cff

![0446d95722272895f4f30600dba89a1b](https://user-images.githubusercontent.com/60679142/104851680-1edfa000-58bc-11eb-8d47-e7000f7b1a16.png)

**Comment by SmashPhil** [comment]
wasn't an issue with Dual Wielding, it's cause you were using a copy from Mod Manager, which I've had issues with in the past and the renaming of the local copies' package id. Fix will be in the next release, thanks
