### ISSUE TITLE
NRE on unloaded tank cannon and entering tank from enter cell

### ISSUE THREAD

**Issue by legodude17** [SmashPhil/Vehicles#36]
**Describe the bug**
When trying to fire a tank cannon without loading a shell, it throws a NullReferenceError.

**To Reproduce**
1. Tank
2. Fully crew it
3. Fire the tank cannon

*Bug 2*
**Describe the bug**
When trying to board a tank from right beside it, it throws a NullReferenceError.

**To Reproduce**
1. Tank
2. Draft someone and put them right next to it, where other pawns go to get in.
3. Attempt to board
[Player.log](https://github.com/SmashPhil/Vehicles/files/5840169/Player.log)

**Comment by SmashPhil** [comment]
This was due to godmode being enabled (which I allowed to override disabling of the turret so I could test rotations without having to reload ammo constantly) This will be removed in the next version and grey out just the gizmo for targeting if ammo is not currently loaded.

**Comment by legodude17** [comment]
What about the second one? Should I just create a new issue?

**Comment by SmashPhil** [comment]
It's fixed. I just need to push out the new version alongside the new health system
