### ISSUE TITLE
Sparrow landed on the map edge instead of chosen spot.

### ISSUE THREAD

**Issue by aleander** [SmashPhil/Vehicles#42]
On one attempt, the sparrow landed in a seemingly random spot around the map edge, instead of the spot I've chosen. Unfortunately several further attempts didn't lead to any repeats.

**Additional context**
Minimal log setup:
* Harmony
* Core
* Royalty
* Mod Manager
* Vehicles

**Comment by SmashPhil** [comment]
tweaked the method used so it picks from the center of the map rather than any random cell.
