### ISSUE TITLE
cannonRenderLocation might need to be mirrored on east / west positions

### ISSUE THREAD

**Issue by juanosarg** [SmashPhil/Vehicles#43]
**Describe the bug**
cannonRenderLocation looks different when the vehicle is facing west and when it is facing east. Roolo ran into the same problem with saddle overlays in Giddy-Up

**To Reproduce**
1. Make tank with a turret with cannonRenderLocation (in the screenie, <cannonRenderLocation>(1,-1)</cannonRenderLocation>)
2. Check in game

**Screenshots**

![imagen](https://user-images.githubusercontent.com/31105173/107355596-008e4e00-6ad0-11eb-9c1f-93a7543c03e3.png)

**Comment by SmashPhil** [comment]
Not sure I understand what you're pointing out. Cannons are a single graphic, so their location rotates along with the vehicle. From what I can see in the screenshot the cannon looks correctly rendered and its location looks fine. Are you talking about how one is top right and the other is bottom left?

**Comment by juanosarg** [comment]
The rotation makes sense if the vehicle graphic is flat, but if it has perspective (I think Oskar called it between top and 60º perspective) the Y coordinate shouldn't be inverted between East and West, and same with the X coordinate between North and South. Not sure how feasible this is, though...

**Comment by SmashPhil** [comment]
I'm sorry but what you're saying makes no sense.  The vehicle is _rotating_ along with its turns. Inverting the x,y coordinates like you mention will create a mirror like effect where the turret will physically change locations relative to the vehicle. The screenshot you posted is exactly how it should be... rotated. This makes sense given the current logic which is to offset by a certain x,y amount that is then inverted based on the rotation (vehicle facing north with (x,y) location will have (-x,-y) location when facing south.

Here is an example with an exaggerated offset
![Screenshot (499)](https://user-images.githubusercontent.com/55668380/108611653-d83f0300-739d-11eb-8f01-69861b822019.png)

Notice how as the vehicle visually rotates clockwise, the turret rotates clockwise with it. If we are to use the same logic, facing west would result in the turret rendering to the north of the vehicle where the last arrow is pointing to.

**Comment by SmashPhil** [comment]
I'll make this change in the next update Sarg, thanks.
