### ISSUE TITLE
Unable of forming Vehicles Caravans

### ISSUE THREAD

**Issue by leugimimi** [SmashPhil/Vehicles#60]
**Describe the bug**
I am unable of forming a Vehicle Caravan. I have tested this with  every vehicle currently available built on the map. and none gets recognized on the caravan screen. boarding a vehicle or drafting it after boarding makes no difference.
I also cant go ahead and add or remove waypoints.

I suppose the feature is not completely implemented yet.

**To Reproduce**

Simply try to make a caravan. no error, but the yellow warning below appeared.

Object with load ID Lord_1 is referenced (xml node name: li) but is not deep-saved. This will cause errors during loading.
Verse.Log:Warning(String, Boolean)
Verse.DebugLoadIDsSavingErrorsChecker:CheckForErrorsAndClear()
Verse.ScribeSaver:FinalizeSaving()
Verse.SafeSaver:DoSave(String, String, Action)
Verse.SafeSaver:Save(String, String, Action, Boolean)
Verse.GameDataSaveLoader:SaveGame(String)
RimWorld.Autosaver:DoAutosave()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Play:Verse.Root_Play.Update_Patch0(Root_Play)

https://pastebin.com/fufFGd0p - the hugslog of the game test

**Screenshots**

![20210412114612_1](https://user-images.githubusercontent.com/28876999/114414074-e5e65d00-9b84-11eb-9cb5-eeb06394c9e2.jpg)
![20210412114407_1](https://user-images.githubusercontent.com/28876999/114414098-eaab1100-9b84-11eb-8713-b54eaa73a86f.jpg)

**Comment by SmashPhil** [comment]
Being unable to choose a route without yet selecting a vehicle is completely intended.  Each vehicle has their own pathing on the world map, so it's impossible to really plan out a path without first yet selecting what vehicles you will be taking.  Your vehicles tab is empty, do you not have any vehicles ingame that belong to your faction?

**Comment by MiguelVitta** [comment]
Yes, I do have vehicles ingame that I built and named, and they don't appear on the vehicles tab. I did test this after some days had passed, and the same thing happened. with cars, ballons, etc. doesn't matter if the vehicles are empty, occupied, or occupied and drafted. 
They simply don't appear in the tab, as per the screenshot on the original post above.

Do the vehicles caravan option work for other people?

**Comment by pantherpusher** [comment]
I'm having the same experience that vehicles won't show up in the vehicles tab

**Comment by SmashPhil** [comment]
I'm working with a couple people in the discord to resolve the issue, as I have not been able to replicate the bug whatsoever.  This will likely be open for awhile until I can figure out what is causing it but I will update the results here. Thanks
