### ISSUE TITLE
AirDefense double load attempt (or invalid ID generation)

### ISSUE THREAD

**Issue by MSeal** [SmashPhil/Vehicles#65]
**Describe the bug**

On first load, sometimes there's a registration error occurring (stack trace below). I'm not sure if the steps to reproduce are consistent or I just got unlucky with 3 tries to think there was a pattern. It might be completely unrelated to Islands but it was what I was testing at the time and only happened on the runs I was making with Island tiles.

**To Reproduce**
1. Launch Rimworld with Biomes Islands mod in combination with Vehicles
2. Create a new map
3. Start on an island (or load an existing island save)
4. See error logged 96 times

**Screenshots**

**Additional context**

I tried with the same mod lost loading a non islands map and it wasn't triggering the same message. Didn't seem to effect immediate gameplay but I haven't gotten to research levels yet where I could tell if vehicles are broken.

```
Cannot register Vehicles.AirDefense Vehicles.AirDefense, (id=AirDefense_Vehicles.AirDefense_-1 in loaded object directory. Id already used by Vehicles.AirDefense Vehicles.AirDefense.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.LoadedObjectDirectory:RegisterLoaded (Verse.ILoadReferenceable)
Verse.CrossRefHandler:ResolveAllCrossReferences ()
Verse.ScribeLoader:FinalizeLoading ()
(wrapper dynamic-method) Verse.Game:Verse.Game.LoadGame_Patch1 (Verse.Game)
(wrapper dynamic-method) Verse.SavedGameLoaderNow:Verse.SavedGameLoaderNow.LoadGameFromSaveFileNow_Patch1 (string)
Verse.Root_Play/<>c:<Start>b__1_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()
```

**Comment by SmashPhil** [comment]
Yea I'm tracking! I just didn't make an issue here.  I'm fixing it when I come back around to the world map stuff again.

Also, for future reference, please include your full logs. I really do appreciate having the full context and the logs provide me that. Thanks 👍

**Comment by MSeal** [comment]
Can do. Let me know if you need that for this one though it sounds like you already have what you need.

**Comment by RolandPlass** [comment]
I think I am getting the same issue. For logs see https://gist.github.com/1ee230fb2ecd8a5daa56be6c05d1cdac
...but honestly they don't look very helpful as the message is just spammed hundreds of times

![grafik](https://user-images.githubusercontent.com/6671808/132122875-494b7a5f-f65b-4ff9-800b-0aa3597c1ea3.png)

**Comment by RolandPlass** [comment]
By the way, this also happens if airdefenses are disabled in the mod settings
![grafik](https://user-images.githubusercontent.com/6671808/132122930-3af11ea9-367f-4abb-85a0-3634c867f891.png)
