### ISSUE TITLE
Can't attack any faction 

### ISSUE THREAD

**Issue by JulekJulas** [SmashPhil/Vehicles#69]
When attacking other faction game kicks me back to the map and says that The caravan couldn't reach the destination and it is too dangerous to re enter for 24 hours. After waiting 24 hours it still doesn't work, When first attacking map generates but dissapears instantly after unpausing, Tried to spawn a colonist there with dev mode but it I still couldn't enter

**Comment by SmashPhil** [comment]
You might not have had a pawn inside your vehicle, can you confirm this? If you did, what steps would you suggest (in order) to recreate this? Thanks.

**Comment by JulekJulas** [comment]
I did have a full crew of 4 people and it didn't happen once I tried it many times on different colonies, What I did is this:
-Started a new colony for testing this mod, Used random pawns, Spawned one more with dev mode, Turned god mode, Placed the tank, Loaded shells into the tank, And made a vehicle caravan to a enemy faction which already was very wonky as the tank couldn't leave the area by itself and told me that it didn't have space and when I helped it leave it teleported all over the place on the map and apparently arrived at the faction half way, Then you know the rest

**Comment by JulekJulas** [comment]
It isn't a compatibility error as only mods I used were Harmony and This mod

**Comment by JulekJulas** [comment]
Also no errors in the log at all just (pawns) caravan couldn't reach destination, It is too dangerous to arrive 24 hours in the top left
My idea is that the tank arrives but instantly leaves because the hitbox is outside and it thinks that you want to leave the area

**Comment by JulekJulas** [comment]
Also it can't enter the main colony as well, Tried reseting rimworlds saves and configs but it didn't work
